### ISSUE TITLE
Agents communication over the www

### ISSUE THREAD

**Issue by georg90** [enmasseio/distribus#1]
Hi!
Great project! I didn't seem to find any forum or other social platform to put my question on..

I'm looking for a way to enable software agents to communicate with each other.
After some playing around (mostly with eve) I didn't see a way to enable them to communicate via the web? My project is a agent based smart home solution. Which will be running on android, linux etc. so eve would be just great!
I don't want to bother about the communication, so let's say one agent sits on Server1 in Ohio while my other agents are all over Europe - how can they communicate with each other without using an explicit URI? Is the some kind of relay network? Or can I define a domain inside the enmasse.io/eve where they can discover each other?

Thanks for any hints to documentation or forum/wiki etc.

**Comment by josdejong** [comment]
Thanks for your input. 

The basic idea of Eve was to let each agent have it's own url and communicate over HTTP. Since then, we have added more ways to communicate. For example the JavaScript implementation of Eve, [evejs](https://github.com/enmasseio/evejs), currently supports the following transports: AMQP, Distribus, HTTP, Local, PubNub, WebSocket.

You will need to address an agent *somehow*, it needs an identifier. This can be an url for HTTP transport, or it can be an agent id over PubNub or Distribus. Eve doesn't contain a discovery service where agents register itself or something like that. These sort of solutions tend to result in a centralistic solution, whilst we want to keep this sort of coordination decentral. So how can agents learn to know about each other? We try to mimic the way humans learn to know each other. When one agent is created by another agent, they can remember each other. When an agent is made part of some group or organization, it can see the other agents in the same group. So in short, we don't have provisioning for learning other agents yet, and you can just create your own "domains" or "joint spaces" where agents can learn to know each other.

**Comment by georg90** [comment]
So I have an agent with an unique id: **agent1_unique**
Then I'll need a Distribus domain where this agent is registered to. 
And now **agent1_unique** will be able to discover agents on the same domain?

**Comment by josdejong** [comment]
Indeed. Agents connected to the same Distribus can send each other messages, no matter on which host they are located. A Distribus can consist of multiple connected hosts, and on each host there can be multiple agents.

Evejs comes with support a number of different transports for messaging. HTTP and WebSockets are mostly used, but require a server/client setup instead of p2p. Using PubNub we could indeed connect a p2p network, though it's a bit of a misuse of the service: it's meant for publish subscribe, one to many messaging, not for one to one message like we want here. It can well be that for your use case evejs + pubnub works just fine. I would love to hear how that works out!

Distribus currently uses WebSockets and therefore can only work between servers. I hope to replace WebSockets with WebRTC, so we can get a p2p setup where hosts do not need to have a public url.

**Comment by georg90** [comment]
Since this is the distribus repository I "moved" my issue: https://github.com/enmasseio/evejs/issues/4
